(function(a){a.fn.extend({maskPassword:function(g){return this.each(function(){var h=function(){f.data("masked")?(f.html(pfund.mask_passwd),c.hide(),d.show(),c.val(d.val()),f.data("masked",!1)):(f.html(pfund.unmask_passwd),d.hide(),c.show(),d.val(c.val()),f.data("masked",!0));return!1},c=function(c){var c=a(c),d=a("<input type='password' />");d.insertAfter(c).attr({id:c.attr("id")+"_mask","class":c.attr("class"),style:c.attr("style")});d.hide();return d}(this),d=a(this),f=a(g);f.toggle(h,h);d.keyup(function(){c.val(d.val())});
c.keyup(function(){d.val(c.val())})})}})})(jQuery);
jQuery(function(a){function g(b){b.type!="dialogclose"&&a(this).dialog("close");a.validationEngine.closePrompt(".formError",!0)}function h(){document.location.href=a("#pfund-login-link").attr("href")}function c(){a("#pfund-wait-dialog").dialog("close");a.validationEngine.buildPrompt("#pfund-register-email",pfund.register_fail,"error")}function d(b){b.success?(a("#pfund-user-login").val(a("#pfund-register-username").val()),a("#pfund-user-pass").val(a("#pfund-register-pass").val()),a("#pfund-login-form").submit()):
(a("#pfund-wait-dialog").dialog("close"),b.errors?(b.errors.invalid_email&&a.validationEngine.buildPrompt("#pfund-register-email",pfund.invalid_email,"error"),b.errors.email_exists&&a.validationEngine.buildPrompt("#pfund-register-email",pfund.email_exists,"error"),b.errors.username_exists&&a.validationEngine.buildPrompt("#pfund-register-username",pfund.username_exists,"error"),b.errors.registerfail&&c()):c())}function f(){var b=a("#pfund-create-account-form");b.validationEngine({returnIsValid:!0,
scroll:!1})&&(a("#pfund-wait-dialog").html(pfund.reg_wait_msg),m(),b.ajaxSubmit({dataType:"json",success:d,error:c}))}function l(){a("#pfund-update-dialog").dialog("close");a("#pfund-register-dialog").dialog({modal:!0,width:300,resizable:!1,buttons:[{text:pfund.register_btn,click:f},{text:pfund.cancel_btn,click:g}],zIndex:99999});a("#pfund-register-pass").maskPassword("#pfund-mask-pass")}function m(){a("#pfund-wait-dialog").dialog({closeOnEscape:!1,draggable:!1,modal:!0,resizable:!1,zIndex:99999})}
function n(b,c,d){if(d.url.indexOf("validate-slug")>-1&&(b=a("."+b.data.errId),(b.length==0||!b.hasClass("ajaxed"))&&j))a(".ui-dialog").dialog("close"),a("#pfund-form").data("dirty",!1),m(),document.pfund_form.submit()}var j=!1,k={modal:!0,resizable:!1,close:g,width:600,buttons:[{text:pfund.ok_btn,click:function(){a(".pfund-camp-locationformError").hasClass("ajaxed")&&a(".pfund-camp-locationformError").removeClass("ajaxed");var b=a("#pfund-form");b.unbind("ajaxSuccess");b.bind("ajaxSuccess",{errId:"pfund-camp-locationformError"},
n);j=b.validationEngine({scroll:!1,returnIsValid:!0})}},{text:pfund.cancel_btn,click:g}],zIndex:99999};a("#pfund-form input").change(function(){j=!1;a("#pfund-form").data("dirty",!0)});a("#pfund-add-dialog").dialog(k);a(".pfund-edit-btn").click(function(){var b=a("#pfund-edit-dialog");b.length>0?b.dialog(k):a("#pfund-add-dialog").dialog(k)});pfund.date_format?a(".pfund-date").datepicker({dateFormat:pfund.date_format}):a(".pfund-date").datepicker();var i=[],e="";a("#pfund-login-link").length==1?(e=
h,pfund.login_fn&&(e=window[pfund.login_fn]),i.push({text:pfund.login_btn,id:"pfund-login-btn",click:e}),a("#pfund-register-link").length==1&&(e=l,pfund.register_fn&&(e=window[pfund.register_fn]),i.push({text:pfund.register_btn,id:"pfund-register-btn",click:e})),e=pfund.continue_editing_btn):e=pfund.ok_btn;i.push({text:e,click:g});a("#pfund-update-dialog").dialog({modal:!0,resizable:!1,buttons:i,zIndex:99999});a("#pfund-register-link").click(l);window.onbeforeunload=function(b){if(a("#pfund-form").data("dirty")){var b=
b||window.event,c=pfund.save_warning;if(b)b.returnValue=c;return c}}});
